"use client";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/layout/sidebar";
import Navbar from "@/components/layout/navbar";
import { useState } from "react";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  const route = pathname.substring(1);
  let [showDrawer, setShowDrawer] = useState(false);

  return (
    <>
      <section className={showDrawer ? `grid grid-cols-12 ` : `flex`}>
        <div className="col-span-2">
          <SideBar
            isOpen={showDrawer}
            onClose={() => setShowDrawer(!showDrawer)}
          ></SideBar>
        </div>
        <div
          className={`${
            route == "dashboard" ? "gap-1" : "gap-6"
          } flex flex-col w-full col-span-10`}
        >
          <Navbar setShowDrawer={setShowDrawer} showDrawer={showDrawer} />
          <main className="">{children}</main>
        </div>
      </section>
    </>
  );
}
