// "use client";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import SideBar from "@/components/layout/sidebar";
// import Navbar from "@/components/layout/navbar";
// import { useState } from "react";
// import { usePathname } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });
// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const pathname = usePathname();
//   const route = pathname.substring(1);
//   const [isModalOpen, setIsModalOpen] = useState(true);
//   let [showDrawer, setShowDrawer] = useState(true);
//   return (
//     <html lang="en">
//       <body
//         className={`${inter.className}`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import BodyWrapper from "@/components/layout/wrapper"; // kita pisah


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <BodyWrapper>{children}</BodyWrapper>
      </ThemeProvider>
    </html>
  );
}
